Fix pre_commit version to avoid exception errors
When updating the conda garage environment, pre_commit gets updated to
v1.14.2, which throws the following exception when trying to push a
commit to the remote repository:

Traceback (most recent call last):
File "/home/aigonzal/miniconda2/envs/garage/bin/pre-commit", line 7,
in <module>
    from pre_commit.main import main
File "/home/aigonzal/miniconda2/envs/garage/lib/python3.6/site-
packages/pre_commit/main.py", line 12, in <module>
    from pre_commit.commands.autoupdate import autoupdate
File "/home/aigonzal/miniconda2/envs/garage/lib/python3.6/site-
packages/pre_commit/commands/autoupdate.py", line 14, in <module>
    from pre_commit.clientlib import CONFIG_SCHEMA
File "/home/aigonzal/miniconda2/envs/garage/lib/python3.6/site-
packages/pre_commit/clientlib.py", line 169, in <module>
    for hook_id, values in _meta
File "/home/aigonzal/miniconda2/envs/garage/lib/python3.6/site-
packages/pre_commit/clientlib.py", line 170, in <listcomp>
    for key, value in values
AttributeError: module 'cfgv' has no attribute 'ConditionalOptional'
error: failed to push some refs to
'https://github.com/rlworkgroup/garage.git'

pre_commit v1.14.2 has cfgv>=1.4.0 as a dependency, but cfgv 1.10 gets
installed when using conda, and that old version of cfgv produces the 
error mentioned above. If pre_commit is installed as a pip dependency
instead of a direct dependency of conda, the right version of cfgv is
installed.
There's no clear reason why pre_commit was not installed by pip before,
so if more errors occur with the pre_commit installation, revert this
commit.